ezrassor:
  # Controller manager configuration   
  controller_manager:
    ros__parameters:
      update_rate: 100
      
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

      arm_front_velocity_controller:
        type: velocity_controllers/JointGroupVelocityController
      
      arm_back_velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

      drum_front_velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

      drum_back_velocity_controller:
        type: velocity_controllers/JointGroupVelocityController

  diff_drive_controller:
    ros__parameters:
      left_wheel_names: ["left_wheel_front_joint", "left_wheel_back_joint"]
      right_wheel_names: ["right_wheel_front_joint", "right_wheel_back_joint"]
    
      wheel_seperation: 0.10
      wheel_radius: 0.18
      wheel_separation_multiplier: 1.0

      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      publish_rate: 50.0
      odom_frame_id: odom
      base_frame_id: base_link

      pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

      open_loop: true
      enable_odom_tf: true

      cmd_vel_timeout: 0.5
      use_stamped_vel: false

      preserve_turning_radius: true

      publish_cmd: true

      publish_wheel_data: true

      linear.x.has_velocity_limits: true
      linear.x.has_acceleration_limits: true
      linear.x.has_jerk_limits: false
      linear.x.max_velocity: 10.0
      linear.x.min_velocity: -10.0
      linear.x.max_acceleration: 2.0
      linear.x.max_jerk: 0.0
      linear.x.min_jerk: 0.0

      angular.z.has_velocity_limits: true
      angular.z.has_acceleration_limits: true
      angular.z.has_jerk_limits: false
      angular.z.max_velocity: 1.0
      angular.z.min_velocity: -1.0
      angular.z.max_acceleration: 1.0
      angular.z.min_acceleration: -1.0
      angular.z.max_jerk: 0.0
      angular.z.min_jerk: 0.0

  arm_front_velocity_controller:
    ros__parameters:
      joints:
        - arm_front_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
      command_interfaces:
        - velocity

      state_interfaces:
        - position
        - velocity
  
  arm_back_velocity_controller:
    ros__parameters:
      joints:
        - arm_back_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
      command_interfaces:
        - velocity

      state_interfaces:
        - position
        - velocity

  drum_front_velocity_controller:
    ros__parameters:
      joints:
       - drum_front_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
      command_interfaces:
        - velocity

      state_interfaces:
        - position
        - velocity  
  
  drum_back_velocity_controller:
    ros__parameters:
      joints:
       - drum_back_joint
      pid: {p: 100.0, i: 0.01, d: 10.0}
      command_interfaces:
        - velocity

      state_interfaces:
        - position
        - velocity  